# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lash < Formula
  desc "Commandline tool to manage PlatformNOW Landscape IDP."
  homepage "https://github.com/platformnow/homebrew-lash"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/platformnow/lash/releases/download/v0.0.5/lash_0.0.5_darwin_arm64.tar.gz"
      sha256 "3a6b195f470582baf6698b96e06b8d63f4590a2a28f385b5b5661dd65db06bfb"

      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformnow/lash/releases/download/v0.0.5/lash_0.0.5_darwin_amd64.tar.gz"
      sha256 "5d986cc081b04fea58d89cc865c74411e633a8ea3ed7bc0570565907dd0bf4bf"

      def install
        bin.install "lash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformnow/lash/releases/download/v0.0.5/lash_0.0.5_linux_arm64.tar.gz"
      sha256 "743c09c662bf23d6dccae57fe7b3e2a4a174bcf70aea1f7f134997f20b84dac4"

      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformnow/lash/releases/download/v0.0.5/lash_0.0.5_linux_amd64.tar.gz"
      sha256 "fcbd7ddf5befa389e498c93f3b64f7c6e7a5f6978b453b0ec9e989342c7f3e6d"

      def install
        bin.install "lash"
      end
    end
  end
end
