# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lash < Formula
  desc "Commandline tool to manage PlatformNOW Landscape IDP."
  homepage "https://github.com/platformnow/homebrew-lash"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/platformnow/lash/releases/download/v0.0.4/lash_0.0.4_darwin_arm64.tar.gz"
      sha256 "062b0b3169f71a550f2bbf1a0a8787c81e891a037b0dc4553c54c8fdfe034c9e"

      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformnow/lash/releases/download/v0.0.4/lash_0.0.4_darwin_amd64.tar.gz"
      sha256 "aadea392647cfb059b22f9c8a2e449bf13490b0d62bda6df1697b37bbdb4e530"

      def install
        bin.install "lash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/platformnow/lash/releases/download/v0.0.4/lash_0.0.4_linux_amd64.tar.gz"
      sha256 "3c7ab558d667118257d3903691363731afd3b4229e486763e39fbcb7d8cc3b16"

      def install
        bin.install "lash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformnow/lash/releases/download/v0.0.4/lash_0.0.4_linux_arm64.tar.gz"
      sha256 "f739323bb8878985d6dd0f4d867730c177c74d19765195ec32e9ed7303829bbd"

      def install
        bin.install "lash"
      end
    end
  end
end
